title: "GeoPython Tutorial"
author: "Pulakesh Pradhan (Content by National Water Academy, Pune)"
logo: ""
execute:
  execute_notebooks: off
  timeout: 300
repository:
  url: "https://github.com/pulakeshpradhan/geopython"
  branch: "main"
html:
  use_repository_button: true
